// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	endpoint "go-microservice-base/users/pkg/endpoint"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeHealthHandler(m, endpoints, options["Health"])

	s := m.PathPrefix("/api/v1/users").Subrouter()
	makeLoginHandler(s, endpoints, options["Login"])
	makeCreateHandler(s, endpoints, options["Create"])
	makeGetByIdHandler(s, endpoints, options["GetById"])

	return m
}
