// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "go-microservice-base/auth/pkg/endpoint"
	pb "go-microservice-base/auth/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	login         grpc.Handler
	logout        grpc.Handler
	validateToken grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.AuthServer {
	return &grpcServer{
		login:         makeLoginHandler(endpoints, options["Login"]),
		logout:        makeLogoutHandler(endpoints, options["Logout"]),
		validateToken: makeValidateTokenHandler(endpoints, options["ValidateToken"]),
	}
}
