// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "fivekilometer/notificator/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	HealthEndpoint endpoint.Endpoint
	NotifyEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.NotificatorService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		HealthEndpoint: MakeHealthEndpoint(s),
		NotifyEndpoint: MakeNotifyEndpoint(s),
	}
	for _, m := range mdw["Health"] {
		eps.HealthEndpoint = m(eps.HealthEndpoint)
	}
	for _, m := range mdw["Notify"] {
		eps.NotifyEndpoint = m(eps.NotifyEndpoint)
	}
	return eps
}
